export const actionType = {
    GET_HOME: 'GET_HOME',
    SET_PAGE_NAME: 'SET_PAGE_NAME',
    SET_ID_DEL: 'SET_ID_DEL',
    SET_IS_HIDE_POPUP_DEL: 'SET_IS_HIDE_POPUP_DEL',
    SET_ID_UPDATE: 'SET_ID_UPDATE',
    SET_DATA_PROFILE: 'SET_DATA_PROFILE',
    SET_POPUP_IMG: 'SET_POPUP_IMG',
    SET_LOGIN_MODE: 'SET_LOGIN_MODE',
    SET_REGISTER_MODE: 'SET_REGISTER_MODE',

    SET_TOKEN: 'SET_TOKEN',
    SET_USER_LOGIN: 'SET_USER_LOGIN',
    LOG_OUT: 'LOG_OUT',
    SET_UPDATE_PROFILE_POPUP: 'SET_UPDATE_PROFILE_POPUP',
    SET_LOADING: 'SET_LOADING',
};
